### ISSUE TITLE
获取验证码报错

### ISSUE THREAD

**Issue by soar20** [MobClub/SMSSDK-for-Flutter#2]
D/SMS_Flutter( 7486): onMethodCall. method: getTextCode
D/SMS_Flutter( 7486): tempCode:
D/SMS_Flutter( 7486): zone: 86
D/SMS_Flutter( 7486): phoneNumber: 13385891038
E/SMS_Flutter( 7486): Smssdk Flutter plugin internal error. msg= Value App of type java.lang.String cannot be converted to JSONObject
E/SMS_Flutter( 7486): org.json.JSONException: Value App of type java.lang.String cannot be converted to JSONObject
E/SMS_Flutter( 7486): 	at org.json.JSON.typeMismatch(JSON.java:111)
E/SMS_Flutter( 7486): 	at org.json.JSONObject.<init>(JSONObject.java:160)
E/SMS_Flutter( 7486): 	at org.json.JSONObject.<init>(JSONObject.java:173)
E/SMS_Flutter( 7486): 	at cn.smssdk.flutter.MobsmsPlugin.onSdkError(MobsmsPlugin.java:315)
E/SMS_Flutter( 7486): 	at cn.smssdk.flutter.MobsmsPlugin.access$100(MobsmsPlugin.java:22)
E/SMS_Flutter( 7486): 	at cn.smssdk.flutter.MobsmsPlugin$1.afterEvent(MobsmsPlugin.java:59)
E/SMS_Flutter( 7486): 	at cn.smssdk.b.a(SMSSDKCore.java:216)
E/SMS_Flutter( 7486): 	at cn.smssdk.b.b(SMSSDKCore.java:284)
E/SMS_Flutter( 7486): 	at cn.smssdk.b.b(SMSSDKCore.java:166)
E/SMS_Flutter( 7486): 	at cn.smssdk.b.a(SMSSDKCore.java:38)
E/SMS_Flutter( 7486): 	at cn.smssdk.b$2.run(SMSSDKCore.java:158)

**Comment by shijiewei** [comment]
你好，可以联系我们的技术支持。
技术支持

服务电话:   400-685-2216     
QQ:        4006852216
节假日值班电话:
    iOS：185-1664-1951
Android: 185-1664-1950
电子邮箱:   support@mob.com
市场合作:   021-54623100

**Comment by shijiewei** [comment]
> D/SMS_Flutter( 7486): onMethodCall. method: getTextCode
> D/SMS_Flutter( 7486): tempCode:
> D/SMS_Flutter( 7486): zone: 86
> D/SMS_Flutter( 7486): phoneNumber: 13385891038
> E/SMS_Flutter( 7486): Smssdk Flutter plugin internal error. msg= Value App of type java.lang.String cannot be converted to JSONObject
> E/SMS_Flutter( 7486): org.json.JSONException: Value App of type java.lang.String cannot be converted to JSONObject
> E/SMS_Flutter( 7486): at org.json.JSON.typeMismatch(JSON.java:111)
> E/SMS_Flutter( 7486): at org.json.JSONObject.(JSONObject.java:160)
> E/SMS_Flutter( 7486): at org.json.JSONObject.(JSONObject.java:173)
> E/SMS_Flutter( 7486): at cn.smssdk.flutter.MobsmsPlugin.onSdkError(MobsmsPlugin.java:315)
> E/SMS_Flutter( 7486): at cn.smssdk.flutter.MobsmsPlugin.access$100(MobsmsPlugin.java:22)
> E/SMS_Flutter( 7486): at cn.smssdk.flutter.MobsmsPlugin$1.afterEvent(MobsmsPlugin.java:59)
> E/SMS_Flutter( 7486): at cn.smssdk.b.a(SMSSDKCore.java:216)
> E/SMS_Flutter( 7486): at cn.smssdk.b.b(SMSSDKCore.java:284)
> E/SMS_Flutter( 7486): at cn.smssdk.b.b(SMSSDKCore.java:166)
> E/SMS_Flutter( 7486): at cn.smssdk.b.a(SMSSDKCore.java:38)
> E/SMS_Flutter( 7486): at cn.smssdk.b$2.run(SMSSDKCore.java:158)

你好，可以联系我们的技术支持。
技术支持

服务电话: 400-685-2216
QQ: 4006852216
节假日值班电话:
iOS：185-1664-1951
Android: 185-1664-1950
电子邮箱: support@mob.com
市场合作: 021-54623100

**Comment by jie0713** [comment]
您联系一下mob官方Q：4006852216 具体有技术支持帮您解答
