### ISSUE TITLE
版本更新后报错

### ISSUE THREAD

**Issue by limhGeek** [MobClub/SMSSDK-for-Flutter#4]
刚集成的时候好好的，突然开始报错了：：

`E/AndroidRuntime(23004): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-1285381
E/AndroidRuntime(23004): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
E/AndroidRuntime(23004): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:727)
E/AndroidRuntime(23004): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:140)
E/AndroidRuntime(23004): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime(23004): 	at cn.smssdk.flutter.MobsmsPlugin.onSuccess(MobsmsPlugin.java:310)
E/AndroidRuntime(23004): 	at cn.smssdk.flutter.MobsmsPlugin.access$000(MobsmsPlugin.java:22)
E/AndroidRuntime(23004): 	at cn.smssdk.flutter.MobsmsPlugin$1.afterEvent(MobsmsPlugin.java:51)
E/AndroidRuntime(23004): 	at cn.smssdk.b.a(SMSSDKCore.java:216)
E/AndroidRuntime(23004): 	at cn.smssdk.b.b(SMSSDKCore.java:284)
E/AndroidRuntime(23004): 	at cn.smssdk.b.b(SMSSDKCore.java:166)
E/AndroidRuntime(23004): 	at cn.smssdk.b.a(SMSSDKCore.java:38)
E/AndroidRuntime(23004): 	at cn.smssdk.b$2.run(SMSSDKCore.java:158)`

**Comment by johngef** [comment]
> 刚集成的时候好好的，突然开始报错了：：
> 
> `E/AndroidRuntime(23004): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-1285381 E/AndroidRuntime(23004): at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794) E/AndroidRuntime(23004): at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:727) E/AndroidRuntime(23004): at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:140) E/AndroidRuntime(23004): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225) E/AndroidRuntime(23004): at cn.smssdk.flutter.MobsmsPlugin.onSuccess(MobsmsPlugin.java:310) E/AndroidRuntime(23004): at cn.smssdk.flutter.MobsmsPlugin.access$000(MobsmsPlugin.java:22) E/AndroidRuntime(23004): at cn.smssdk.flutter.MobsmsPlugin$1.afterEvent(MobsmsPlugin.java:51) E/AndroidRuntime(23004): at cn.smssdk.b.a(SMSSDKCore.java:216) E/AndroidRuntime(23004): at cn.smssdk.b.b(SMSSDKCore.java:284) E/AndroidRuntime(23004): at cn.smssdk.b.b(SMSSDKCore.java:166) E/AndroidRuntime(23004): at cn.smssdk.b.a(SMSSDKCore.java:38) E/AndroidRuntime(23004): at cn.smssdk.b$2.run(SMSSDKCore.java:158)`

自己先改一下吧，在https://github.com/MobClub/SMSSDK-for-Flutter/blob/master/android/src/main/java/cn/smssdk/flutter/MobsmsPlugin.java文件里，有关result.success()的地方放在UI线程中调用就可以了

**Comment by jie0713** [comment]
您联系一下mob官方Q：4006852216
