### ISSUE TITLE
刚集成的时候好好的，突然开始报错了!!!

### ISSUE THREAD

**Issue by dmskys** [MobClub/SMSSDK-for-Flutter#5]
刚集成的时候好好的，突然开始报错了：

E/AndroidRuntime(10125): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-31
E/AndroidRuntime(10125): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:795)
E/AndroidRuntime(10125): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:728)
E/AndroidRuntime(10125): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:156)
E/AndroidRuntime(10125): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime(10125): 	at cn.smssdk.flutter.MobsmsPlugin.onSdkError(MobsmsPlugin.java:328)
E/AndroidRuntime(10125): 	at cn.smssdk.flutter.MobsmsPlugin.access$100(MobsmsPlugin.java:22)
E/AndroidRuntime(10125): 	at cn.smssdk.flutter.MobsmsPlugin$1.afterEvent(MobsmsPlugin.java:59)
E/AndroidRuntime(10125): 	at cn.smssdk.b.a(SMSSDKCore.java:216)
E/AndroidRuntime(10125): 	at cn.smssdk.b.b(SMSSDKCore.java:284)
E/AndroidRuntime(10125): 	at cn.smssdk.b.b(SMSSDKCore.java:166)
E/AndroidRuntime(10125): 	at cn.smssdk.b.a(SMSSDKCore.java:38)
E/AndroidRuntime(10125): 	at cn.smssdk.b$2.run(SMSSDKCore.java:158)

**Comment by jie0713** [comment]
您联系一下mob官方Q：4006852216
